# Generated by Django 3.1.6 on 2021-02-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('correo', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('contrasena', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('correo', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('contrasena', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=60)),
            ],
        ),
    ]
