# Generated by Django 3.1.6 on 2021-02-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
