# Generated by Django 3.1.6 on 2021-02-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo',
        ),
    ]
