# Generated by Django 3.1.6 on 2021-02-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_producto', models.CharField(max_length=40)),
                ('Nombre', models.CharField(max_length=40)),
                ('Vendeor', models.CharField(max_length=35)),
                ('Cantidad', models.IntegerField()),
                ('Descripcion', models.TextField(max_length=350)),
            ],
        ),
    ]
