# Generated by Django 3.1.6 on 2021-02-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Vendeor',
            new_name='Vendedor',
        ),
    ]
