# Generated by Django 3.1.6 on 2021-02-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210205_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Precio',
            field=models.FloatField(default='1.00'),
        ),
    ]
