# Generated by Django 3.1.6 on 2021-02-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_producto', models.CharField(max_length=40)),
                ('Nombre', models.CharField(max_length=40)),
                ('Vendedor', models.CharField(max_length=35)),
                ('Comprador', models.CharField(max_length=40)),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.FloatField(default='1.00')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
